import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import ToasterProvider from "@/providers/ToasterProvider";
import getActiveProductsWithPrices from "@/actions/getActiveProductsWithPrices";
import getSongsByUserId from "@/actions/getSongsByUserId";
const font = Figtree({ subsets: ["latin"] });
import Player from "@/components/Player";

export const metadata: Metadata = {
  title: "Spotify Clone",
  description: "Generated by create next app",
};

export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const products = await getActiveProductsWithPrices();
  const userSongs = await getSongsByUserId();

  return (
    <html lang="en">
      <body className={font.className}>
        {/* now we could access to our database by this provider */}
        <ToasterProvider />
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider products={products} />
            {/* <ModalProvider /> */}
            <Sidebar songs={userSongs}>{children}</Sidebar>
            {/* </ModalProvider> */}
            <Player />
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
